// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oz.Infrastructure.Data;

#nullable disable

namespace Oz.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702132840_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Oz.Domain.Entities.GradeStage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SchoolId", "Name")
                        .IsUnique();

                    b.ToTable("GradeStages");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(699),
                            IsActive = true,
                            Name = "KG1",
                            NameAr = "كي جي 1",
                            SchoolId = 1L,
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1103)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1397),
                            IsActive = true,
                            Name = "KG2",
                            NameAr = "كي جي 2",
                            SchoolId = 1L,
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1397)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1398),
                            IsActive = true,
                            Name = "KG3",
                            NameAr = "كي جي 3",
                            SchoolId = 1L,
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1399)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1453),
                            IsActive = true,
                            Name = "FS1",
                            NameAr = "صف اول",
                            SchoolId = 1L,
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1453)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1454),
                            IsActive = true,
                            Name = "FS2",
                            NameAr = "صف ثاني",
                            SchoolId = 1L,
                            SortOrder = 5,
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1455)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1456),
                            IsActive = true,
                            Name = "FS3",
                            NameAr = "صف ثالث",
                            SchoolId = 1L,
                            SortOrder = 6,
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1456)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1458),
                            IsActive = true,
                            Name = "FS4",
                            NameAr = "صف رابع",
                            SchoolId = 1L,
                            SortOrder = 7,
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1458)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1459),
                            IsActive = true,
                            Name = "FS5",
                            NameAr = "صف خامس",
                            SchoolId = 1L,
                            SortOrder = 8,
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1460)
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1461),
                            IsActive = true,
                            Name = "FS6",
                            NameAr = "صف سادس",
                            SchoolId = 1L,
                            SortOrder = 9,
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(1461)
                        });
                });

            modelBuilder.Entity("Oz.Domain.Entities.ItemType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ItemTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4016),
                            IsActive = true,
                            Name = "T-Shirt",
                            NameAr = "تي شيرت",
                            Slug = "t-shirt",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4392)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4758),
                            IsActive = true,
                            Name = "Polo",
                            NameAr = "بولو",
                            Slug = "polo",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4759)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4760),
                            IsActive = true,
                            Name = "Shirt",
                            NameAr = "قميص",
                            Slug = "shirt",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4760)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4762),
                            IsActive = true,
                            Name = "Trousers",
                            NameAr = "بنطلون",
                            Slug = "trousers",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4762)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4763),
                            IsActive = true,
                            Name = "Shorts",
                            NameAr = "شورت",
                            Slug = "shorts",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4764)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4765),
                            IsActive = true,
                            Name = "Skirt",
                            NameAr = "تنورة",
                            Slug = "skirt",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4765)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4766),
                            IsActive = true,
                            Name = "Pinafore",
                            NameAr = "مريلة",
                            Slug = "pinafore",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4767)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4768),
                            IsActive = true,
                            Name = "Sweater",
                            NameAr = "سترة",
                            Slug = "sweater",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4768)
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4769),
                            IsActive = true,
                            Name = "Tracksuit",
                            NameAr = "بدلة رياضية",
                            Slug = "tracksuit",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4770)
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4771),
                            IsActive = true,
                            Name = "Socks",
                            NameAr = "جوارب",
                            Slug = "socks",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 752, DateTimeKind.Utc).AddTicks(4771)
                        });
                });

            modelBuilder.Entity("Oz.Domain.Entities.School", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 751, DateTimeKind.Utc).AddTicks(690),
                            IsActive = true,
                            Name = "Cairo Language School",
                            NameAr = "مدرسة القاهرة للغات",
                            Slug = "cairo-language-school",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 751, DateTimeKind.Utc).AddTicks(1071)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 751, DateTimeKind.Utc).AddTicks(1432),
                            IsActive = true,
                            Name = "Alexandria Experimental",
                            NameAr = "مدرسة الإسكندرية التجريبية",
                            Slug = "alexandria-experimental",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 751, DateTimeKind.Utc).AddTicks(1432)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 751, DateTimeKind.Utc).AddTicks(1434),
                            IsActive = true,
                            Name = "Giza Arabic School",
                            NameAr = "مدرسة الجيزة العربية",
                            Slug = "giza-arabic-school",
                            UpdatedAt = new DateTime(2026, 7, 2, 13, 28, 39, 751, DateTimeKind.Utc).AddTicks(1434)
                        });
                });

            modelBuilder.Entity("Oz.Domain.Entities.GradeStage", b =>
                {
                    b.HasOne("Oz.Domain.Entities.School", "School")
                        .WithMany("GradeStages")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Oz.Domain.Entities.School", b =>
                {
                    b.Navigation("GradeStages");
                });
#pragma warning restore 612, 618
        }
    }
}
